### ISSUE TITLE
"Torrent" word on the main phrase of the website

### ISSUE THREAD

**Issue by prcastro** [popcorn-official/popcorn-site-legacy#36]
Many users don't know what torrent mean, or failed to use it properly. I think we could remove this word from this phrase, without losing the meaning of it.

**Comment by berdesos** [comment]
I was thinking of the same thing. On the other hand it may be necessary to mention it since the users should be aware that the streaming movies are coming from torrents and that may be illegal in their countries. But I guess mentioning it in other parts of the page would compensate for the removal of the word. So +1

**Comment by fxbt** [comment]
Plus, it make it hard to translate in other languages. There is a warning on the front page. It's enough.

![](http://i.imgur.com/RscVDBX.png)
