### ISSUE TITLE
No need to self-link

### ISSUE THREAD

**Issue by notpushkin** [popcorn-official/popcorn-site-legacy#56]
There's a link in footer that leads to the same page. I don't know if we need it, but chances are it's redundant.

![Screenshot](https://cloud.githubusercontent.com/assets/1298948/3294845/b871533c-f5b1-11e3-8a3a-a39a3f1576e2.png)

**Comment by frdmn** [comment]
Thanks @iamale, but I think this is purposed and personally i wouldn't change that either. It's a consistent footer across the most "web services" of PT. If anyone of the team disagree, reopen this issue :)

**Comment by notpushkin** [comment]
Hmm, seems logical. But there are some flaws.
1. In fact this footer is present only on main website (index, FAQ, ToS) and blog pages. No footer on [status page](http://status.popcorntime.io/), no footer on [forum](http://discuss.popcorntime.io/) (I guess this should be separate issue).
2. This link duplicates the Popcorn Time logo functionality (on the left), as it links to the same page, so it's really not needed. 
   ![The Footer](https://cloud.githubusercontent.com/assets/1298948/3298333/5202f296-f600-11e3-9b70-748cf56a2e70.png)
3. Even if you leave it, the icon is ambiguous. Octocat = 'our page on GitHub', Twitter bird = 'our Twitter', Pochoclin = 'our page on Popcorn Time'? Strange. 

P. S. I won't reopen, as I'm not 'from the team', neither I can mention the team (the org has no public members), so it's up to you. :smile:

**Comment by frdmn** [comment]
My thoughts on this:
1. Correct, but it wouldn't make sense to add a footer in Discourse because its built for endless scrolling to reload new content. So you wouldn't reach the end of the page anyway except for for meta pages and discussions that doesn't have that much posts. But as you already said: should go into a new issue :)
2. I don't have a problem with that "redundancy" at all actually, but I get your point. 
3. See it like this: "Our GitHub profile", "Our Twitter account", "Our web site". 

@xeoncore what do you think?

**Comment by ghost** [comment]
True, but to be honest, no one will really care if its there twice. The idea was to use a standardized footer across all our platforms so that it was consistent and familiar to our users. 

If it is really a big issue, it can be changed, but I don't have a problem with it.

**Comment by notpushkin** [comment]
Fine then.
